# Generated by Django 5.1.6 on 2025-07-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='password',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
