# Generated by Django 5.1.6 on 2025-07-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0002_instauser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='gmail',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
