# Generated by Django 5.1.6 on 2025-07-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0003_instauser_gmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='dob',
            field=models.DateField(default=''),
        ),
    ]
