# Generated by Django 5.1.6 on 2025-07-12 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0004_alter_instauser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='dob',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
    ]
